### ISSUE TITLE
bug: steam://connect link not working

### ISSUE THREAD

**Issue by Dr3nz4r** [a-sync/game-server-watcher#15]
**Describe the bug**
unlike the screenshots, the address is not a steam join link

**Steps To Reproduce**
Add a server with the json config from below

**Expected behavior**
the Address field should be a clickable steam:// join link

**Screenshots or Data**
![image](https://github.com/a-sync/game-server-watcher/assets/75803461/fb810cfe-cbab-4ce6-a88e-cdebccc1d7cc)

Json config
```json
{
  "name": "Server Name",
  "type": "cs2",
  "host": "Server Host",
  "port": 27015,
  "appId": 730,
  "graphHistoryHours": 12,
  "discord": [
    {
      "channelId": "1234",
      "showPlayersList": true,
      "showGraph": true,
      "onlineColor": "#00ff00",
      "offlineColor": "#000000"
    }
  ],
  "telegram": [ ],
  "requestRules": true,
  "requestRulesRequired": true,
  "requestPlayersRequired": true
}
```

**Comment by a-sync** [comment]
hey,
i removed the steam:// prefix from the address field because it's not correct/working for non steam games.

i have plans to allow customization of the embed fields via configuration, but for now, if you want this the quickest way would be to edit the discord-bot source and put it back in.

the embed is created here: https://github.com/a-sync/game-server-watcher/blob/8197f27491d3f4dfd82cdaf6efd666ade10bd5df/src/discord-bot.ts#L181
and the line you want would look something like this:  
```
fields.push({ name: 'Address', value: String('steam://connect/' + gs.info.connect)});
```

if you need this to run in ptero, for now i suggest you create a fork, make changes there, and then edit the ptero egg install script line that starts with `git clone https:` to point to your own fork instead of mine (a-sync/game-server-watcher). then install a new server with the new egg.

**Comment by Dr3nz4r** [comment]
That's exactly my use case, thanks a lot!
